
import MealsPage from '../components/MealsPage';

export const metadata = {
    title: {
      absolute: "Meals Page",
    },
    description: "Generated by create next app",
    keywords: "Meals|| Meals Page"
  };

const page = () => {
    
    return (
     <div>
<MealsPage></MealsPage>
     </div>
    );

}
export default page;